apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite-exporter
  namespace: prometheus
  labels:
    app.kubernetes.io/component: graphite-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: graphite-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: graphite-exporter
    spec:
      containers:
        - image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: graphite-exporter
          volumeMounts:
            - name: config
              mountPath: /config
          volumes:
            - name: config
              configMap:
                name: graphite-config
                items:
                  - key: config.conf
                    path: /conf/config.conf
          ports:
            - containerPort: 9108
              name: eight
              protocol: TCP
            - containerPort: 9109
              name: data
              protocol: TCP
            - containerPort: 9109
              name: data
              protocol: UDP