apiVersion: v1
kind: Service
metadata:
  name: graphite-exporter
  namespace: prometheus
  labels:
    app.kubernetes.io/component: graphite-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: graphite-exporter
  ports:
    - name: data
      port: 9108
      protocol: TCP
      targetPort: 9108
