# library chart values are purely for documentation purposes

argoconfig:
  application:
    - name: opensearch
      spec:
        project: default
        source:
          repoURL: https://opensearch-project.github.io/helm-charts
          targetRevision: 2.26.1
          helm:
            values: |-
              ingress:
                enabled: true
                className: "cilium"
                annotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hosts:
                    - host: opensearch.homelab
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                  - secretName: opensearch-tls
                    hosts:
                      - opensearch.homelab
          chart: opensearch
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: opensearch
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: hivemq-mqtt-platform
      spec:
        project: default
        source:
          repoURL: https://hivemq.github.io/helm-charts
          targetRevision: 0.2.21
          helm:
            values: |-
              replicaCount: 1
          chart: hivemq-platform
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: hivemq
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: hivemq-mqtt-operator
      spec:
        project: default
        source:
          repoURL: https://hivemq.github.io/helm-charts
          targetRevision: 0.2.9
          helm:
            values: |-
              replicaCount: 1
                
          chart: hivemq-platform-operator
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: hivemq
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: homeassistant
      spec:
        project: default
        source:
          repoURL: 'https://pajikos.github.io/home-assistant-helm-chart'
          targetRevision: 0.2.72
          helm:
            values: |-
              ingress:
                # Enable ingress for home assistant
                enabled: true
                className: "cilium"
                annotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hosts:
                    - host: homeassistant.homelab
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                  - secretName: homeassistant-tls
                    hosts:
                      - homeassistant.homelab

              configuration:
                enabled: true
                forceInit: false
                trusted_proxies:
                  - 10.0.0.0/8
                  - 192.0.0.0/8

              persistence:
                enabled: true
                size: "10Gi"

          chart: home-assistant
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: homeassistant
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: vaultwarden
      spec:
        project: default
        source:
          repoURL: 'https://guerzon.github.io/vaultwarden'
          targetRevision: 0.23.1
          helm:
            values: |-
              domain: "https://vaultwarden.homelab"
              ingress:
                enabled: true
                class: cilium
                additionalAnnotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hostname: vaultwarden.homelab
                tlsSecret: vaultwarden-tls
          chart: vaultwarden
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: vaultwarden
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
    - name: prometheus
      spec:
        project: default
        source:
          repoURL: 'https://prometheus-community.github.io/helm-charts'
          targetRevision: 61.7.1
          helm:
            values: |-
              grafana:
                enabled: true
                ingress:
                  enabled: true
                  ingressClassName: cilium
                  annotations:
                    ingress.cilium.io/loadbalancer-mode: shared
                    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                  hosts:
                    - grafana.homelab
                  tls:
                    - secretName: grafana-tls
                      hosts:
                        - grafana.homelab
          chart: kube-prometheus-stack
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: prometheus
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
