# library chart values are purely for documentation purposes

argoconfig:
  application:
    - name: nextcloud
      enabled: false
      spec:
        project: default
        source:
          repoURL: https://nextcloud.github.io/helm/
          targetRevision: 6.5.2
          helm:
            values: |-

          chart: nextcloud
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: nextcloud
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true

    - name: portainer
      enabled: true
      spec:
        project: default
        source:
          repoURL: https://portainer.github.io/k8s/
          targetRevision: 1.0.58
          helm:
            values: |-
              enterpriseEdition: 
                enabled: true
                image:
                  repository: portainer/portainer-ee
                  tag: 2.21.5
                  pullPolicy: Always
              ingress:
                enabled: true
                ingressClassName: cilium
                annotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hosts:
                  - host: portainer.homelab
                    paths:
                      - path: "/"
                tls: 
                  - secretName: portainer-tls
                    hosts:
                      - portainer.homelab

          chart: portainer
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: portainer
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
    - name: pihole6
      enabled: true 
      spec:
        project: default
        source: 
          #repoURL: https://mojo2600.github.io/pihole-kubernetes
          #targetRevision: 2.27.0
          repoURL: https://github.com/paimonsoror/pihole-kubernetes.git
          path: charts/pihole
          targetRevision: HEAD
          helm:
            values: |-
              image:
                # -- the repostory to pull the image from
                repository: "pihole/pihole"
                # -- the docker tag, if left empty it will get it from the chart's appVersion
                tag: "latest"
              admin:
                enabled: true
                existingSecret: pihole-password
                passwordKey: "password"
              virtualHost: pihole.homelab
              DNS1: "1.1.1.1"
              DNS2: "1.0.0.1"
              serviceDns:
                annotations:             
                  io.cilium/lb-ipam-ips: 192.168.5.102
                  io.cilium/lb-ipam-sharing-key: pi-hole
                type: LoadBalancer
              serviceDhcp:
                annotations:             
                  io.cilium/lb-ipam-ips: 192.168.5.102
                  io.cilium/lb-ipam-sharing-key: pi-hole
                type: LoadBalancer
              serviceWeb:
                annotations:             
                  io.cilium/lb-ipam-ips: 192.168.5.102
                  io.cilium/lb-ipam-sharing-key: pi-hole
                http:
                  enabled: true
                https:
                  enabled: false
                type: LoadBalancer
              ingress:
                enabled: false
                ingressClassName: cilium
                annotations:
                  ingress.cilium.io/loadbalancer-mode: dedicated
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hosts:
                  - pihole.homelab
                path: /
                pathType: Prefix
                tls: 
                  - secretName: pihole-tls
                    hosts:
                      - pihole.homelab
              dnsmasq:
                additionalDnsEntries:
                  - address=/pihole.homelab/192.168.5.102
                  - address=/pihole.pi/192.168.3.2
                additionalHostsEntries:
                  - 127.0.0.1 pihole.homelab
              persistentVolumeClaim:
                enabled: true
                existingClaim: pihole-pvc
              extraVolumes:
                custom-dnsmasq-dir:
                  persistentVolumeClaim:
                    claimName: pihole-dnsmasq-pvc
              extraVolumeMounts:
                custom-dnsmasq-dir:
                  mountPath: /etc/dnsmasq.d    
          chart: pihole
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: pihole
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
    - name: fluentbit
      enabled: false
      spec:
        project: default
        source:
          repoURL: https://fluent.github.io/helm-charts
          targetRevision: 3.2.0
          helm:
            values: |-
              fluentbit:
                output:
                  es:
                    enable: true
                    host: opensearch-cluster-master.opensearch.svc.cluster.local
                    port: 9200
                    generateID: true
                    logstashPrefix: fluent-log-fb-only
                    logstashFormat: true
                    timeKey: "@timestamp"
                    enableTLS: true
                    suppressTypeName: "On"
                    index: "fluent-bit"
                    tls:
                      verify: false
                    httpUser: 
                      valueFrom: 
                        secretKeyRef:
                          name: opensearchpass
                          key: username
                    httpPassword:
                      valueFrom: 
                        secretKeyRef:
                          name: opensearchpass
                          key: password
          chart: fluent-operator
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: fluent
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
    - name: immich
      enabled: true
      spec:
        project: default
        source:
          repoURL: https://immich-app.github.io/immich-charts
          targetRevision: 0.8.4
          helm:
            values: |-
              image:
                tag: v1.126.1
              immich:
                metrics:
                  enabled: true
                persistence:
                  library:
                    existingClaim: immich-pvc
              postgresql:
                enabled: true
                primary:
                  resources:
                    requests:
                      cpu: 200m
                      memory: 512Mi
                    limits:
                      cpu: 400m
                      memory: 1024Mi
              redis:
                enabled: true
              server:
                enabled: true
                image:
                  repository: ghcr.io/immich-app/immich-server
                  pullPolicy: IfNotPresent
                ingress:
                  main:
                    enabled: true
                    ingressClassName: "cilium"
                    annotations:
                      ingress.cilium.io/loadbalancer-mode: shared
                      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                    hosts:
                      - host: immich.homelab
                        paths:
                          - path: "/"
                    tls: 
                      - secretName: immich-tls
                        hosts:
                          - immich.homelab
          chart: immich
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: immich
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: opensearch-dashboards
      enabled: false
      spec:
        project: default
        source:
          repoURL: https://opensearch-project.github.io/helm-charts
          targetRevision: 2.24.1
          helm:
            values: |-
              ingress:
                enabled: true
                ingressClassName: "cilium"
                annotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hosts:
                    - host: opensearch-dash.homelab
                      paths:
                        - path: /
                          backend:
                            serviceName: ""
                            servicePort: ""
                tls:
                  - secretName: opensearch-dash-tls
                    hosts:
                      - opensearch-dash.homelab
          chart: opensearch-dashboards
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: opensearch
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: opensearch
      enabled: false
      spec:
        project: default
        source:
          repoURL: https://opensearch-project.github.io/helm-charts
          targetRevision: 2.26.1
          helm:
            values: |-
              secretMounts:
                - name: opensearch-tls
                  secretName: opensearch-tls
                  path: /usr/share/opensearch/config/certs
              config:
                opensearch.yml: |
                  cluster.name: opensearch-cluster

                  # Bind to all interfaces because we don't know what IP address Docker will assign to us.
                  network.host: 0.0.0.0

                  # Setting network.host to a non-loopback address enables the annoying bootstrap checks. "Single-node" mode disables them again.
                  # Implicitly done if ".singleNode" is set to "true".
                  # discovery.type: single-node

                  # Start OpenSearch Security Demo Configuration
                  # WARNING: revise all the lines below before you go into production
                  plugins:
                    security:
                      ssl:
                        transport:
                          pemcert_filepath: certs/esnode.pem
                          pemkey_filepath: certs/esnode-key.pem
                          pemtrustedcas_filepath: certs/root-ca.pem
                          enforce_hostname_verification: false
                        http:
                          enabled: true
                          pemcert_filepath: certs/esnode.pem
                          pemkey_filepath: certs/esnode-key.pem
                          pemtrustedcas_filepath: certs/root-ca.pem
                      allow_unsafe_democertificates: true
                      allow_default_init_securityindex: true
                      authcz:
                        admin_dn:
                          - CN=kirk,OU=client,O=client,L=test,C=de
                      audit.type: internal_opensearch
                      enable_snapshot_restore_privilege: true
                      check_snapshot_restore_write_privileges: true
                      restapi:
                        roles_enabled: ["all_access", "security_rest_api_access"]
                      system_indices:
                        enabled: true
                        indices:
                          [
                            ".opendistro-alerting-config",
                            ".opendistro-alerting-alert*",
                            ".opendistro-anomaly-results*",
                            ".opendistro-anomaly-detector*",
                            ".opendistro-anomaly-checkpoints",
                            ".opendistro-anomaly-detection-state",
                            ".opendistro-reports-*",
                            ".opendistro-notifications-*",
                            ".opendistro-notebooks",
                            ".opendistro-asynchronous-search-response*",
                          ]
                  ######## End OpenSearch Security Demo Configuration ########
              persistence:
                enabled: false
              singleNode: true
              extraEnvs: 
                - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
                  value: Th1s1sS3cure
              ingress:
                enabled: true
                ingressClassName: "cilium"
                annotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                path: /
                hosts:
                    - opensearch.homelab
                tls:
                  - secretName: opensearch-tls
                    hosts:
                      - opensearch.homelab
          chart: opensearch
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: opensearch
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: hivemq-mqtt-platform
      enabled: true
      spec:
        project: default
        source:
          repoURL: https://hivemq.github.io/helm-charts
          targetRevision: 0.2.21
          helm:
            values: |-
              replicaCount: 1
          chart: hivemq-platform
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: hivemq
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: hivemq-mqtt-operator
      enabled: true
      spec:
        project: default
        source:
          repoURL: https://hivemq.github.io/helm-charts
          targetRevision: 0.2.9
          helm:
            values: |-
              replicaCount: 1
                
          chart: hivemq-platform-operator
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: hivemq
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: homeassistant
      enabled: true
      spec:
        project: default
        source:
          repoURL: 'https://pajikos.github.io/home-assistant-helm-chart'
          targetRevision: 0.2.102
          helm:
            values: |-
              ingress:
                # Enable ingress for home assistant
                enabled: true
                className: "cilium"
                annotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hosts:
                    - host: homeassistant.homelab
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                  - secretName: homeassistant-tls
                    hosts:
                      - homeassistant.homelab

              configuration:
                enabled: true
                forceInit: false
                trusted_proxies:
                  - 10.0.0.0/8
                  - 192.0.0.0/8

              persistence:
                enabled: true
                size: "10Gi"
                existingVolume: homeassistant-pv-volume

          chart: home-assistant
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: homeassistant
        syncPolicy:
          automated: {}
          syncOptions:
            - CreateNamespace=true
    - name: vaultwarden
      enabled: true
      spec:
        project: default
        source:
          repoURL: 'https://github.com/paimonsoror/vaultwarden.git'
          targetRevision: main
          path: charts/vaultwarden
          helm:
            values: |-
              domain: "https://vaultwarden.homelab"
              storage:
                existingVolumeClaim: 
                  claimName: vaultwarden-pvc
              ingress:
                enabled: true
                class: cilium
                additionalAnnotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hostname: vaultwarden.homelab
                tlsSecret: vaultwarden-tls
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: vaultwarden
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
    - name: prom-push-gateway
      enabled: true
      spec:
        project: default
        source:
          repoURL: 'https://prometheus-community.github.io/helm-charts'
          targetRevision: 2.15.0
          helm:
            values: |-
              ingress:
                enabled: true
                className: cilium
                pathType: Prefix
                annotations:
                  ingress.cilium.io/loadbalancer-mode: shared
                  cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                hosts:
                  - prompushgtwy.homelab
                tls:
                  - secretName: prompush-tls
                    hosts:
                      - prompushgtwy.homelab
          chart: prometheus-pushgateway
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: prometheus
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
    - name: prometheus
      enabled: true
      spec:
        project: default
        source:
          repoURL: 'https://prometheus-community.github.io/helm-charts'
          targetRevision: 61.7.1
          helm:
            values: |-
              prometheus:
                enabled: true
                prometheusSpec:
                  additionalScrapeConfigs:
                    - job_name: "netdata-exporter"
                      metrics_path: '/api/v1/allmetrics'
                      params:
                        # format: prometheus | prometheus_all_hosts
                        # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostname instead of IP 
                        format: [ prometheus ]
                        #
                        # sources: as-collected | raw | average | sum | volume
                        # default is: average
                        #source: [as-collected]
                        #
                        # server name for this prometheus - the default is the client IP
                        # for Netdata to uniquely identify it
                        #server: ['prometheus1']
                      honor_labels: true

                      static_configs:
                        - targets: [ 'truenas.homelab:20489' ]
              grafana:
                enabled: true
                ingress:
                  enabled: true
                  ingressClassName: cilium
                  annotations:
                    ingress.cilium.io/loadbalancer-mode: shared
                    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
                  hosts:
                    - grafana.homelab
                  tls:
                    - secretName: grafana-tls
                      hosts:
                        - grafana.homelab
          chart: kube-prometheus-stack
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: prometheus
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
            - ServerSideApply=true
