apiVersion: v1
kind: Service
metadata:
  name: {{ include "technitium-exporter.fullname" . }}
  labels:
    {{- include "technitium-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "technitium-exporter.selectorLabels" . | nindent 4 }}
