{{- range $v := .Values.argoconfig.application }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: {{$v.name}}
  namespace: argocd
spec:
  {{- toYaml $v.spec | nindent 2 }}
{{- end }}